import {ImageSource, Sound} from "excalibur";

export const images = {
    bolt: new ImageSource(require("./bolt.png")),
    bolt2: new ImageSource(require("./bolt2.png")),
    hero_idle: new ImageSource(require("./hero_idle.png")),
    heroExias_idle: new ImageSource(require("./Exias_idleV4.png")),
    hero_run: new ImageSource(require("./hero_run.png")),
    heroExias_run: new ImageSource(require("./Exias_runningV2.png")),
    hero_jump: new ImageSource(require("./hero_jump.png")),
    hero_down: new ImageSource(require("./hero_down.png")),
    hero_attack: new ImageSource(require("./hero_attack.png")),
    hero_attack_down: new ImageSource(require("./hero_down_attack.png")),
    hero_attack_jump: new ImageSource(require("./hero_jump_attack.png")),
    rose: new ImageSource(require("./rose.png")),
    fox: new ImageSource(require("./fox.png")),
    mirror: new ImageSource(require("./mirror.png")),
    mage: new ImageSource(require("./skeleton_mage.png")),
    war: new ImageSource(require("./skeleton_warrior.png")),
    bubble: new ImageSource(require("./bubble.png")),
    crystal: new ImageSource(require("./red_crystal.png")),
    xiao: new ImageSource(require("./xiao.png")),
    dragon: new ImageSource(require("./dragon.png")),
    kstore: new ImageSource(require("./kstore.png")),
    acidpop: new ImageSource(require("./acidpop.png")),
    shrek: new ImageSource(require("./shrek.png")),
    inf1: new ImageSource(require("./inf1.png")),
    inf2: new ImageSource(require("./inf2.png")),
    //
    avatar_fox: new ImageSource(require("./avatar/fox.png")),
    avatar_xiao: new ImageSource(require("./avatar/xiao.png")),
    avatar_dragon: new ImageSource(require("./avatar/dragon.png")),
    avatar_kstore: new ImageSource(require("./avatar/kstore.png")),
    avatar_acidpop: new ImageSource(require("./avatar/acidpop.png")),
    avatar_shrek: new ImageSource(require("./avatar/shrek.png")),
    avatar_skeleton: new ImageSource(require("./avatar/skeleton.png")),
    avatar_chest: new ImageSource(require("./avatar/chest.png")),
}

export const sounds = {
    sky: new Sound(require("./audio/sky.mp3")),
    s2043: new Sound(require("./audio/2043.wav")),
    s2045: new Sound(require("./audio/2045.wav")),
    firebolt: new Sound(require("./audio/firebolt.wav")),
    jump_0: new Sound(require("./audio/1010100_03_cn.ogg")),
    jump_1: new Sound(require("./audio/1010100_04_cn.ogg")),
    jump_2: new Sound(require("./audio/1010100_05_cn.ogg")),
    fox_1: new Sound(require("./audio/357_01_en.ogg")),
    fox_2: new Sound(require("./audio/357_02_en.ogg")),
    fox_3: new Sound(require("./audio/357_03_en.ogg")),
    hero_dead: new Sound(require("./audio/500003_cn.ogg")),
    s264: new Sound(require("./audio/264.WAV")),
    s268: new Sound(require("./audio/268.WAV")),
    s270: new Sound(require("./audio/270.WAV")),
    s278: new Sound(require("./audio/278.WAV")),
    s279: new Sound(require("./audio/279.WAV")),
    s281: new Sound(require("./audio/281.WAV")),
    s282: new Sound(require("./audio/282.WAV")),
    s283: new Sound(require("./audio/283.WAV")),
    transi: new Sound(require("./audio/transi.wav")),
    crystal: new Sound(require("./audio/crystal.wav")),
    boom: new Sound(require("./audio/boom.wav")),
    hit_light: new Sound(require("./audio/hit_light.wav")),
    //
    music_1: new Sound(require("./audio/crystalsong.mp3")),
    music_army: new Sound(require("./audio/music_army.ogg")),
    music_dragon: new Sound(require("./audio/music_dragon.mp3")),
    music_soldier: new Sound(require("./audio/music_soldier.ogg")),
    music_boss: new Sound(require("./audio/music_boss.mp3")),
    music_end: new Sound(require("./audio/music_end.ogg")),
}